
INSERT INTO books (book_name, author, isbn, price, pages, binding, year_publishing, book_language)
VALUES         ('it starts us', 'Collen Hoover', '978-1668001226', 11.99, 366, 'solid', 2022, 'ENGLISH','in stock'),
               ('I train update books', 'Collen Hoover', '978-1533723738', 11.99, 326, 'solid', 2019, 'RUSSIAN','in stock'),
               ('Beautiful Ruins', 'Jess Walter', '978-1668001228', 13.79, 372, 'solid', 2014, 'RUSSIAN','in stock'),
               ('Ugly love', 'Collen Hooveer', '978-1476753188', 11.86, 437, 'soft', 2004, 'SPANISH','in stock'),
               ('Every Summer After', 'Carley Fortune', '978-0593438534', 11.40, 320, 'solid', 2020, 'FRENCH','in stock'),
               ('The Very Hungry Caterpillar', 'Eric Carle', '978-0399226908', 5.74, 26, 'soft', 2013, 'CHINESE','in stock'),
               ('Book Lovers', 'Emily Henry', ' 978-0593334836', 9.99, 400, 'solid', 2015, 'CHINESE','in stock'),
               ('Big Prescool', 'Joan Hoffman', '978-0887431456', 5.99, 420, 'solid', 2022, 'ENGLISH','in stock'),
               ('The Silent Patient', 'Alex Michaelides', '978-1250301703', 12.99, 368, 'solid', 2019, 'ENGLISH','in stock'),
               ('The Power of Now', 'Eckhart Tolle', '978-1577314806', 11.99, 236, 'soft', 2021, 'ENGLISH','in stock'),
               ('The Lord of the Rings Part One', 'J.R.R. Tolkien', '978-0063270886', 14.89, 432, 'solid', 2016, 'RUSSIAN','in stock'),
               ('Fire & Blood: 300 Years Before A Game of Thrones', 'George R. R. Martin', '978-0063270835', 24.89, 754, 'solid', 2014, 'RUSSIAN','in stock'),
               ('Maybe Someday', 'Colleen Hoover', '978-1476753164', 11.62, 384, 'solid', 2017, 'JAPANESE','in stock'),
               ('Harry Potter Spellbook: The Unofficial ', 'Newt Flamel', '979-8447208332', 7.95, 100, 'solid', 2021, 'ENGLISH','in stock'),
               ('Harry Potter and the Goblet of Fire ', 'J. K. Rowling', '978-0545791427', 13.99, 464, 'solid', 2021, 'ENGLISH','in stock'),
                ('Harry Potter and the Sorcerer Stone', 'J. K. Rowling', '978-0545791422', 13.13, 345, 'solid', 2019, 'ENGLISH','in stock'),
                ('Harry Potter and the Chamber of Secrets', 'J. K. Rowling', '978-1338716535', 7.80, 400, 'solid', 2017,'SPANISH','in stock'),
                ('Sparring Partners: Novellas', 'John Grisham', '978-1338715534', 16.50, 350, 'soft', 2009, 'ENGLISH','in stock'),
                ('A Time for Mercy', 'John Grisham', '978-1338725536', 7.50, 469, 'soft', 2010, 'ENGLISH','in stock'),
                ('Mastering the Art of French Cooking', 'Julia Child', '978-1238725736', 19.50, 1244, 'soft', 2015, 'FRENCH','in stock'),
                ('A Letter From Your Teacher: On the First Day of School', 'Shannon Olsen', '978-1735414126', 13.99, 31, 'soft', 2007, 'ENGLISH','in stock');


INSERT INTO users (first_name, last_name, user_age, email, user_role)
VALUES ('Nik', 'Swanson', 35, 'n.sw@gmail.com', 'ADMIN'),
       ('Nik', 'Meclo', 24, 'n.mcl@gmail.com', 'ADMIN'),
       ('Sam', 'Growner', 42, 's.gr_4@mail.com', 'USER'),
       ('Wane', 'Rooney', 39, 'WR.10@gmail.com', 'MANAGER'),
       ('Mike', 'Ramcey', 28, 'm.rmc@gmail.com', 'USER'),
       ('Samanta', 'Robson', 42, 'samanta_rob123@gmail.com', 'ADMIN'),
       ('Selena', 'Gomes', 43, 'selena_love_sing@gmail.com', 'USER'),
       ('Raley', 'Rricey', 56, 'ral.12387@mail.com', 'MANAGER'),
       ('Brad', 'Spacey', 35, 'br_spacey.com', 'ADMIN'),
       ('Helena', 'Rassy', 42, 'helena.ras456@gmail.com', 'USER'),
       ('Mike', 'Walent', 50, 'mik.walent@mail.com', 'MANAGER'),
       ('Stasey', 'Lacatelli', 35, 'locat.ital12@gmail.com', 'ADMIN'),
       ('Jeck', 'Peterson', 46, 'pet.jeck1987@gmail.com', 'USER'),
       ('Molly', 'Swanson', 22, 'swans.mol1999@gmail.com', 'USER'),
       ('Rob', 'Jeferson', 17, 'jeferson19991999@gmail.com', 'USER'),
       ('Jim', 'Paranga', 40, 'par.jim_1998@mail.com', 'USER'),
       ('Samanta', 'Metry', 35, 'sam.petry15678@gmail.com', 'ADMIN'),
       ('Sam', 'Cook', 19, 'cokky_sam1987@gmail.com', 'USER'),
       ('Wolly', 'Monson', 59, 'monson_1967@gmail.com', 'MANAGER'),
       ('Nik', 'Cracks', 49, 'cr_nik_1979@gmail.com', 'ADMIN'),
       ('Silly', 'Sorento', 42, 'sil.srn18@gmail.com', 'USER');

INSERT INTO orders (user_id, total_cost, status)
VALUES ((SELECT id FROM users WHERE email = 'n.sw@gmail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'n.mcl@gmail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 's.gr_4@mail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'WR.10@gmail.com'), 0.0, 'CONFIRMED'),
       ((SELECT id FROM users WHERE email = 'm.rmc@gmail.com'), 0.0, 'CONFIRMED'),
       ((SELECT id FROM users WHERE email = 'samanta_rob123@gmail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'selena_love_sing@gmail.com'), 0.0, 'CONFIRMED'),
       ((SELECT id FROM users WHERE email = 'ral.12387@mail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'br_spacey.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'helena.ras456@gmail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'mik.walent@mail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'locat.ital12@gmail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'pet.jeck1987@gmail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'swans.mol1999@gmail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'jeferson19991999@gmail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'par.jim_1998@mail.com'), 0.0, 'PENDING'),
       ((SELECT id FROM users WHERE email = 'sam.petry15678@gmail.com'), 0.0, 'CONFIRMED'),
       ((SELECT id FROM users WHERE email = 'cokky_sam1987@gmail.com'), 0.0, 'CONFIRMED'),
       ((SELECT id FROM users WHERE email = 'monson_1967@gmail.com'), 0.0, 'CONFIRMED'),
       ((SELECT id FROM users WHERE email = 'cr_nik_1979@gmail.com'), 0.0, 'CONFIRMED'),
       ((SELECT id FROM users WHERE email = 'sil.srn18@gmail.com'), 0.0, 'CONFIRMED'),
       ((SELECT id FROM users WHERE email = 'n.sw@gmail.com'), 0.0, 'PENDING');

INSERT INTO order_items (order_id, book_id, quantity, price)
VALUES (1, (SELECT id FROM books WHERE book_name = 'it starts us'),2, (SELECT price FROM books WHERE book_name = 'it starts us')),
       (1, (SELECT id FROM books WHERE book_name = 'I train update books'),2, (SELECT price FROM books WHERE book_name = 'I train update books')),
       (2, (SELECT id FROM books WHERE book_name = 'I train update books'),1, (SELECT price FROM books WHERE book_name = 'I train update books')),
       (2, (SELECT id FROM books WHERE book_name = 'Beautiful Ruins'),1, (SELECT price FROM books WHERE book_name = 'Beautiful Ruins')),
       (3, (SELECT id FROM books WHERE book_name = 'Beautiful Ruins'),2, (SELECT price FROM books WHERE book_name = 'Beautiful Ruins')),
       (3, (SELECT id FROM books WHERE book_name = 'it starts us'),1, (SELECT price FROM books WHERE book_name = 'it starts us')),
       (4, (SELECT id FROM books WHERE book_name = 'Ugly love'),1, (SELECT price FROM books WHERE book_name = 'Ugly love')),
       (4, (SELECT id FROM books WHERE book_name = 'I train update books'),3, (SELECT price FROM books WHERE book_name = 'I train update books')),
       (5, (SELECT id FROM books WHERE book_name = 'Beautiful Ruins'),1, (SELECT price FROM books WHERE book_name = 'Beautiful Ruins')),
       (5, (SELECT id FROM books WHERE book_name = 'I train update books'),3, (SELECT price FROM books WHERE book_name = 'I train update books')),
       (6, (SELECT id FROM books WHERE book_name = 'Beautiful Ruins'),2, (SELECT price FROM books WHERE book_name = 'Beautiful Ruins')),
       (6, (SELECT id FROM books WHERE book_name = 'Big Prescool'),2, (SELECT price FROM books WHERE book_name = 'Big Prescool')),
       (7, (SELECT id FROM books WHERE book_name = 'Beautiful Ruins'),3, (SELECT price FROM books WHERE book_name = 'Beautiful Ruins')),
       (8, (SELECT id FROM books WHERE book_name = 'Big Prescool'),2, (SELECT price FROM books WHERE book_name = 'Big Prescool')),
       (9, (SELECT id FROM books WHERE book_name = 'Beautiful Ruins'),1, (SELECT price FROM books WHERE book_name = 'Beautiful Ruins')),
       (9, (SELECT id FROM books WHERE book_name = 'Big Prescool'),2, (SELECT price FROM books WHERE book_name = 'Beautiful Ruins')),
       (10, (SELECT id FROM books WHERE book_name = 'Harry Potter and the Goblet of Fire '),2, (SELECT price FROM books WHERE book_name = 'Harry Potter and the Goblet of Fire ')),
       (10, (SELECT id FROM books WHERE book_name = 'Big Prescool'),1, (SELECT price FROM books WHERE book_name = 'Beautiful Ruins')),
       (11, (SELECT id FROM books WHERE book_name = 'it starts us'),2, (SELECT price FROM books WHERE book_name = 'it starts us')),
       (12, (SELECT id FROM books WHERE book_name = 'A Time for Mercy'),3, (SELECT price FROM books WHERE book_name = 'A Time for Mercy')),
       (13, (SELECT id FROM books WHERE book_name = 'Maybe Someday'),3, (SELECT price FROM books WHERE book_name = 'Maybe Someday')),
       (14, (SELECT id FROM books WHERE book_name = 'Maybe Someday'),2, (SELECT price FROM books WHERE book_name = 'Maybe Someday')),
       (15, (SELECT id FROM books WHERE book_name = 'A Time for Mercy'),1, (SELECT price FROM books WHERE book_name = 'A Time for Mercy')),
       (16, (SELECT id FROM books WHERE book_name = 'it starts us'),3, (SELECT price FROM books WHERE book_name = 'it starts us')),
       (17, (SELECT id FROM books WHERE book_name = 'A Time for Mercy'),2, (SELECT price FROM books WHERE book_name = 'A Time for Mercy')),
       (18, (SELECT id FROM books WHERE book_name = 'A Time for Mercy'),3, (SELECT price FROM books WHERE book_name = 'A Time for Mercy')),
       (19, (SELECT id FROM books WHERE book_name = 'Maybe Someday'),2, (SELECT price FROM books WHERE book_name = 'Maybe Someday')),
       (20, (SELECT id FROM books WHERE book_name = 'A Time for Mercy'),2, (SELECT price FROM books WHERE book_name = 'A Time for Mercy')),
       (21, (SELECT id FROM books WHERE book_name = 'it starts us'),5, (SELECT price FROM books WHERE book_name = 'it starts us')),
       (22, (SELECT id FROM books WHERE book_name = 'it starts us'),2, (SELECT price FROM books WHERE book_name = 'it starts us'));